import {
	Calendar16,
	CheckmarkOutline16,
	CopyLink16,
	DirectionMerge16,
	Document16,
	Enterprise16,
	Error16,
	EventSchedule16,
	FlowData16,
	Forum16,
	GroupPresentation16,
	Identification16,
	Link16,
	Microphone16,
	Partnership16,
	Recommend16,
	Stamp16,
	User16,
	// @ts-ignore
} from '@carbon/icons-vue';

export const nodeIconMap = new Map([
	['Bill', Document16],
	['BillEnforceEvent', CheckmarkOutline16],
	['BillMergeEvent', DirectionMerge16],
	['BillRejectEvent', Error16],
	['BillRoyalAssentEvent', Stamp16],
	['DraftVoteEvent', EventSchedule16],
	['Event', Calendar16],
	['Link', Link16],
	['LinkOwner', CopyLink16],
	['Member', Partnership16],
	['Membership', Identification16],
	['Motion', FlowData16],
	['MotionProposer', GroupPresentation16],
	['Organization', Enterprise16],
	['Person', User16],
	['Post', Recommend16],
	['Vote', Microphone16],
	['VoteEvent', Forum16],
]);
