import {
	Calendar16,
	CheckmarkOutline16,
	CopyLink16,
	DirectionMerge16,
	Document16,
	Error16,
	Events16,
	EventSchedule16,
	FlowData16,
	GroupPresentation16,
	Identification16,
	Link16,
	Partnership16,
	Portfolio16,
	Stamp16,
	User16,
	UserProfileAlt16,
	VoiceActivate16,
	// @ts-ignore
} from '@carbon/icons-vue';

export const nodeIconMap = new Map([
	['Bill', Document16],
	['BillEnforceEvent', CheckmarkOutline16],
	['BillMergeEvent', DirectionMerge16],
	['BillRejectEvent', Error16],
	['BillRoyalAssentEvent', Stamp16],
	['DraftVoteEvent', EventSchedule16],
	['Event', Calendar16],
	['Link', Link16],
	['LinkOwner', CopyLink16],
	['Member', Partnership16],
	['Membership', Identification16],
	['Motion', FlowData16],
	['MotionProposer', UserProfileAlt16],
	['Organization', Events16],
	['Person', User16],
	['Post', Portfolio16],
	['Vote', VoiceActivate16],
	['VoteEvent', GroupPresentation16],
]);
