services:
  nginx:
    image: jonasal/nginx-certbot:5.4.0-alpine
    container_name: nginx
    restart: always
    depends_on:
      - nuxt
    volumes:
      - ./nginx.conf:/etc/nginx/user_conf.d/web.conf:ro
      - /var/htdocs:/var/htdocs
      - letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    environment:
      CERTBOT_EMAIL: team@wevis.info
    privileged: true

  nuxt:
    container_name: politigraph-nuxt
    image: wevisdemo/politigraph:latest
    restart: always
    depends_on:
      - neo4j
    env_file:
      - '.env'
    environment:
      NEO4J_HOST: neo4j
      NUXT_PUBLIC_BASE_URL: https://politigraph.wevis.info
    volumes:
      - betterauth:/app/.better-auth
    ports:
      - 3000:3000

  neo4j:
    extends:
      file: compose.yml
      service: neo4j
    container_name: politigraph-neo4j
    restart: always
    volumes:
      - ./neo4j-data:/data
    labels:
      - docker-volume-backup.stop-during-backup=true

  do-agent:
    image: digitalocean/do-agent:stable
    container_name: do-agent
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro

  backup:
    image: offen/docker-volume-backup:v2
    container_name: backup
    restart: always
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/backup:/archive
      - betterauth:/backup/betterauth:ro
      - ./neo4j-data:/backup/neo4j:ro
    environment:
      BACKUP_CRON_EXPRESSION: 0 21 * * 5
      BACKUP_COMPRESSION: zst
      BACKUP_RETENTION_DAYS: 30
      AWS_S3_BUCKET_NAME: puwv-backup
      AWS_S3_PATH: wevis-politigraph
      AWS_STORAGE_CLASS: STANDARD_IA
    env_file:
      - '.backup.env'

volumes:
  betterauth:
  letsencrypt:
