services:
  elysia:
    image: wevisdemo/politigraph:latest
    container_name: elysia
    restart: always
    depends_on:
      - neo4j
      - postgres
    volumes:
      - ./tls:/app/tls:ro
      - /var/htdocs/assets:/app/public/assets:ro
    environment:
      BETTER_AUTH_SECRET: $BETTER_AUTH_SECRET
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@127.0.0.1:5432/betterauth
      NEO4J_USERNAME: $NEO4J_USERNAME
      NEO4J_PASSWORD: $NEO4J_PASSWORD
      PORT: 443
      SIGN_UP_TOKEN: $SIGN_UP_TOKEN
    privileged: true
    network_mode: 'host'

  neo4j:
    extends:
      file: compose.yml
      service: neo4j
    container_name: neo4j
    restart: always
    volumes:
      - ./neo4j/data:/data
    labels:
      - docker-volume-backup.stop-during-backup=true
    privileged: true
    network_mode: 'host'

  postgres:
    extends:
      file: compose.yml
      service: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: betterauth
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    labels:
      - docker-volume-backup.stop-during-backup=true
    network_mode: 'host'

  do-agent:
    image: digitalocean/do-agent:stable
    container_name: do-agent
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    network_mode: 'host'

  backup:
    image: offen/docker-volume-backup:v2
    container_name: backup
    restart: always
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/backup:/archive
      - postgres:/backup/postgres:ro
      - ./neo4j/data:/backup/neo4j:ro
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_S3_BUCKET_NAME: puwv-backup
      AWS_S3_PATH: wevis-politigraph
      AWS_STORAGE_CLASS: STANDARD_IA
      BACKUP_COMPRESSION: zst
      BACKUP_CRON_EXPRESSION: 0 21 * * 5
      BACKUP_RETENTION_DAYS: 30
    network_mode: 'host'

volumes:
  postgres:
