services:
  nginx:
    image: jonasal/nginx-certbot:5.4.0-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/user_conf.d/web.conf:ro
      - letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    environment:
      CERTBOT_EMAIL: team@wevis.info
    privileged: true
  nuxt:
    container_name: politigraph-nuxt
    image: wevisdemo/politigraph:latest
    depends_on:
      - neo4j
    env_file:
      - '.env'
    environment:
      NEO4J_HOST: neo4j
      NUXT_PUBLIC_BASE_URL: https://politigraph.wevis.info
    volumes:
      - betterauth:/app/.better-auth
    ports:
      - 3000:3000
  neo4j:
    extends:
      file: compose.yml
      service: neo4j
    container_name: politigraph-neo4j
    volumes:
      - neo4j:/data

  do-agent:
    image: digitalocean/do-agent:stable
    container_name: do-agent
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro

volumes:
  betterauth:
  letsencrypt:
  neo4j:
