services:
  neo4j:
    image: neo4j:5.25.1
    volumes:
      - .neo4j/logs:/logs
      - .neo4j/config:/config
      - .neo4j/data:/data
      - .neo4j/plugins:/plugins
      - .neo4j/import:/import
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_apoc_import_file_use__neo4j__config: true
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474"
      - "7687:7687"
