// Available icons: https://v10.carbondesignsystem.com/guidelines/icons/library/
import {
	Calendar16,
	Chat16,
	ChatBot16,
	CheckmarkOutline16,
	CopyLink16,
	DirectionMerge16,
	Document16,
	Error16,
	Event16,
	Events16,
	EventSchedule16,
	FlowData16,
	Forum16,
	GroupPresentation16,
	Identification16,
	Link16,
	Partnership16,
	Portfolio16,
	Stamp16,
	Tag16,
	User16,
	UserProfileAlt16,
	VoiceActivate16,
	// @ts-ignore
} from '@carbon/icons-vue';

export const nodeIconMap = new Map([
	['AlternateName', Chat16],
	['AlternatePersonName', ChatBot16],
	['Bill', Document16],
	['BillEvent', Event16],
	['BillEnactEvent', CheckmarkOutline16],
	['BillMergeEvent', DirectionMerge16],
	['BillRejectEvent', Error16],
	['BillRoyalAssentEvent', Stamp16],
	['BillVoteEvent', EventSchedule16],
	['Event', Calendar16],
	['Link', Link16],
	['LinkOwner', CopyLink16],
	['Member', Partnership16],
	['Membership', Identification16],
	['Motion', FlowData16],
	['MotionCreator', UserProfileAlt16],
	['NamedEntity', Tag16],
	['Organization', Events16],
	['OtherNames', Forum16],
	['Person', User16],
	['Post', Portfolio16],
	['Vote', VoiceActivate16],
	['VoteEvent', GroupPresentation16],
]);
