name: Build and deploy app

on:
  push:
    branches: ['main']
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'servers/db/*'
      - '.github/workflows/db.yml'
      - 'scripts/*'
  workflow_dispatch:

jobs:
  build-api:
    name: Build API image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build image
        run: docker build -t wevisdemo/politigraph .
      - name: Save image
        run: docker save wevisdemo/politigraph | gzip > politigraph-image.tar.gz
      - name: Upload image and configs to server
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -azvP --chown=bot:deployer --chmod=g+w
          path: servers/app/compose.yml servers/app/nginx.conf politigraph-image.tar.gz
          remote_host: ${{ secrets.SSH_APP_HOST }}
          remote_user: bot
          remote_key: ${{ secrets.SSH_KEY }}
          remote_path: ${{ secrets.SSH_BACKEND_DIR }}
  migrate-database:
    name: Migrate database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --ignore-scripts --production
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Open SSH tunnel
        run: ssh -f -N -M -S /tmp/tunnel-socket -o StrictHostKeyChecking=no -o ControlMaster=yes -L 5432:127.0.0.1:5432 bot@${{ secrets.SSH_DB_HOST }}
      - name: Run auth migrations
        working-directory: packages/auth
        env:
          DATABASE_URL: 'postgresql://${{ secrets.POSTGRES_CREDENTIAL }}@127.0.0.1:5432/betterauth'
        run: bun run migrate
      - name: Close SSH tunnel
        run: ssh -S /tmp/tunnel-socket -O exit bot@${{ secrets.SSH_DB_HOST }}
  update-server:
    name: Update server containers
    runs-on: ubuntu-latest
    needs:
      - build-api
      - migrate-database
    steps:
      - name: Update server containers
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_APP_HOST }}
          username: bot
          key: ${{ secrets.SSH_KEY }}
          script: |
            #!/usr/bin/env bash
            set -e
            cd ${{ secrets.SSH_BACKEND_DIR }}
            docker image tag wevisdemo/politigraph:latest wevisdemo/politigraph:previous
            docker load --input politigraph-image.tar.gz
            docker compose up -d --remove-orphans
            docker exec nginx sh -c "nginx -t && nginx -s reload"
            docker container prune --force
            docker image prune --all --force --filter "until=72h"
  frontend:
    name: Build and deploy frontend
    runs-on: ubuntu-latest
    needs:
      - update-server
    steps:
      - uses: actions/checkout@v6
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --ignore-scripts --production
      - name: Build frontend apps
        run: bun run build --filter=@politigraph/admin --filter=@politigraph/docs
        env:
          NODE_ENV: production
          NUXT_PUBLIC_BASE_URL: https://politigraph.wevis.info
      - name: Upload admin to server
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -azvP --chown=bot:deployer --chmod=g+w --delete
          path: ./apps/admin/.output/public/*
          remote_host: ${{ secrets.SSH_APP_HOST }}
          remote_user: bot
          remote_key: ${{ secrets.SSH_KEY }}
          remote_path: ${{ secrets.SSH_FRONTEND_DIR }}/admin
      - name: Upload docs to server
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -azvP --chown=bot:deployer --chmod=g+w --delete
          path: ./apps/docs/dist/*
          remote_host: ${{ secrets.SSH_APP_HOST }}
          remote_user: bot
          remote_key: ${{ secrets.SSH_KEY }}
          remote_path: ${{ secrets.SSH_FRONTEND_DIR }}/docs
