name: Push image and deploy to staging

on:
  push:
    branches: ['main']
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to the registry
        run: docker login --username wevisdemo --password ${{ secrets.DOCKER_TOKEN }}
      - name: Build image
        run: docker build -t wevisdemo/politigraph .
      - name: Push image to the registry
        run: docker push wevisdemo/politigraph
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Upload compose files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: bot
          key: ${{ secrets.SSH_KEY }}
          source: 'compose.yml,compose.server.yml'
          target: ${{ secrets.SSH_APP_DIR }}
      - name: Update server containers
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: bot
          key: ${{ secrets.SSH_KEY }}
          script: |
            #!/usr/bin/env bash
            set -e
            cd ${{ secrets.SSH_APP_DIR }}
            docker login --username wevisdemo --password ${{ secrets.DOCKER_TOKEN }}
            docker compose -f compose.server.yml pull --quiet
            docker compose -f compose.server.yml up -d
            docker logout
